//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANNUNCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANNUNCIO()
        {
            this.ANNUNCIO11 = new HashSet<ANNUNCIO>();
            this.ANNUNCIO12 = new HashSet<ANNUNCIO>();
            this.ANNUNCIO_CARRELLO = new HashSet<ANNUNCIO_CARRELLO>();
            this.ANNUNCIO_CLICK = new HashSet<ANNUNCIO_CLICK>();
            this.ANNUNCIO_DESIDERATO = new HashSet<ANNUNCIO_DESIDERATO>();
            this.ANNUNCIO_FEEDBACK = new HashSet<ANNUNCIO_FEEDBACK>();
            this.ANNUNCIO_FOTO = new HashSet<ANNUNCIO_FOTO>();
            this.ANNUNCIO_NOTIFICA = new HashSet<ANNUNCIO_NOTIFICA>();
            this.ANNUNCIO_TAG = new HashSet<ANNUNCIO_TAG>();
            this.ANNUNCIO_TIPO_SCAMBIO = new HashSet<ANNUNCIO_TIPO_SCAMBIO>();
            this.ANNUNCIO_VISUALIZZAZIONE = new HashSet<ANNUNCIO_VISUALIZZAZIONE>();
            this.OFFERTA = new HashSet<OFFERTA>();
            this.OFFERTA_BARATTO = new HashSet<OFFERTA_BARATTO>();
            this.TRANSAZIONE_ANNUNCIO = new HashSet<TRANSAZIONE_ANNUNCIO>();
            this.LOG_SBLOCCO_ANNUNCIO = new HashSet<LOG_SBLOCCO_ANNUNCIO>();
        }
    
        public int ID { get; set; }
        public System.Guid TOKEN { get; set; }
        public int ID_CATEGORIA { get; set; }
        public Nullable<int> ID_OGGETTO { get; set; }
        public Nullable<int> ID_SERVIZIO { get; set; }
        public int ID_PERSONA { get; set; }
        public Nullable<int> ID_ATTIVITA { get; set; }
        public int TIPO_PAGAMENTO { get; set; }
        public string NOME { get; set; }
        public int PUNTI { get; set; }
        public Nullable<int> SOLDI { get; set; }
        public string URL_SCHEDA { get; set; }
        public string NOTE_AGGIUNTIVE { get; set; }
        public Nullable<int> ID_COMUNE { get; set; }
        public Nullable<int> ID_PADRE { get; set; }
        public Nullable<int> ID_ORIGINE { get; set; }
        public int NO_OFFERTE { get; set; }
        public int RIMETTI_IN_VENDITA { get; set; }
        public System.DateTime DATA_AVVIO { get; set; }
        public Nullable<System.DateTime> DATA_FINE { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
        public Nullable<int> ID_TIPO_VALUTA { get; set; }
        public string SESSIONE_COMPRATORE { get; set; }
        public Nullable<int> ID_COMPRATORE { get; set; }
        public Nullable<System.DateTime> DATA_VENDITA { get; set; }
    
        public virtual ANNUNCIO ANNUNCIO1 { get; set; }
        public virtual ANNUNCIO ANNUNCIO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO> ANNUNCIO11 { get; set; }
        public virtual ANNUNCIO ANNUNCIO3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO> ANNUNCIO12 { get; set; }
        public virtual ANNUNCIO ANNUNCIO4 { get; set; }
        public virtual ATTIVITA ATTIVITA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_CARRELLO> ANNUNCIO_CARRELLO { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_CLICK> ANNUNCIO_CLICK { get; set; }
        public virtual COMUNE COMUNE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_DESIDERATO> ANNUNCIO_DESIDERATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_FEEDBACK> ANNUNCIO_FEEDBACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_FOTO> ANNUNCIO_FOTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_NOTIFICA> ANNUNCIO_NOTIFICA { get; set; }
        public virtual OGGETTO OGGETTO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual SERVIZIO SERVIZIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_TAG> ANNUNCIO_TAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_TIPO_SCAMBIO> ANNUNCIO_TIPO_SCAMBIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_VISUALIZZAZIONE> ANNUNCIO_VISUALIZZAZIONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFERTA> OFFERTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFERTA_BARATTO> OFFERTA_BARATTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAZIONE_ANNUNCIO> TRANSAZIONE_ANNUNCIO { get; set; }
        public virtual TIPO_VALUTA TIPO_VALUTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_SBLOCCO_ANNUNCIO> LOG_SBLOCCO_ANNUNCIO { get; set; }
        public virtual PERSONA PERSONA1 { get; set; }
    }
}
