//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANNUNCIO_TIPO_SCAMBIO_SPEDIZIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANNUNCIO_TIPO_SCAMBIO_SPEDIZIONE()
        {
            this.TRANSAZIONE_ANNUNCIO_SPEDIZIONE = new HashSet<TRANSAZIONE_ANNUNCIO_SPEDIZIONE>();
        }
    
        public int ID { get; set; }
        public int ID_ANNUNCIO_TIPO_SCAMBIO { get; set; }
        public int ID_CORRIERE_SERVIZIO_SPEDIZIONE { get; set; }
        public int ID_TIPO_OGGETTO { get; set; }
        public decimal PUNTI { get; set; }
        public decimal SOLDI { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual ANNUNCIO_TIPO_SCAMBIO ANNUNCIO_TIPO_SCAMBIO { get; set; }
        public virtual CORRIERE_SERVIZIO_SPEDIZIONE CORRIERE_SERVIZIO_SPEDIZIONE { get; set; }
        public virtual TIPO_OGGETTO TIPO_OGGETTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAZIONE_ANNUNCIO_SPEDIZIONE> TRANSAZIONE_ANNUNCIO_SPEDIZIONE { get; set; }
    }
}
