//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTIVITA_INDIRIZZO_SPEDIZIONE
    {
        public int ID { get; set; }
        public int ID_ATTIVITA_INDIRIZZO { get; set; }
        public string NOMINATIVO { get; set; }
        public string TELEFONO { get; set; }
        public string INFO_EXTRA { get; set; }
        public Nullable<int> TEMPO_IMBALLAGGIO { get; set; }
        public string GIORNI_DISPONIBILITA_SPEDIZIONE { get; set; }
        public string ORARI_DISPONIBILITA_SPEDIZIONE { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual ATTIVITA_INDIRIZZO ATTIVITA_INDIRIZZO { get; set; }
        public virtual ATTIVITA_INDIRIZZO_SPEDIZIONE ATTIVITA_INDIRIZZO_SPEDIZIONE1 { get; set; }
        public virtual ATTIVITA_INDIRIZZO_SPEDIZIONE ATTIVITA_INDIRIZZO_SPEDIZIONE2 { get; set; }
    }
}
