//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTIVITA_INDIRIZZO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATTIVITA_INDIRIZZO()
        {
            this.ATTIVITA_INDIRIZZO_SPEDIZIONE = new HashSet<ATTIVITA_INDIRIZZO_SPEDIZIONE>();
        }
    
        public int ID { get; set; }
        public int ID_ATTIVITA { get; set; }
        public int ID_INDIRIZZO { get; set; }
        public int TIPO { get; set; }
        public int ORDINE { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual ATTIVITA ATTIVITA { get; set; }
        public virtual INDIRIZZO INDIRIZZO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTIVITA_INDIRIZZO_SPEDIZIONE> ATTIVITA_INDIRIZZO_SPEDIZIONE { get; set; }
    }
}
