//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORRIERE_SERVIZIO_PREZZO_STIMATO
    {
        public int ID { get; set; }
        public int ID_CORRIERE_SERVIZIO { get; set; }
        public int PESO_MINIMO { get; set; }
        public Nullable<int> PESO_MASSIMO { get; set; }
        public decimal PREZZO_STIMATO { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual CORRIERE_SERVIZIO CORRIERE_SERVIZIO { get; set; }
    }
}
