//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORRIERE_SERVIZIO_SPEDIZIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CORRIERE_SERVIZIO_SPEDIZIONE()
        {
            this.ANNUNCIO_TIPO_SCAMBIO_SPEDIZIONE = new HashSet<ANNUNCIO_TIPO_SCAMBIO_SPEDIZIONE>();
        }
    
        public int ID { get; set; }
        public int ID_CORRIERE_SERVIZIO { get; set; }
        public int ID_TIPO_PACCO { get; set; }
        public Nullable<int> ID_INDIRIZZO_MITTENTE { get; set; }
        public string NOMINATIVO_MITTENTE { get; set; }
        public string TELEFONO_MITTENTE { get; set; }
        public string INFO_EXTRA_MITTENTE { get; set; }
        public Nullable<int> TEMPO_IMBALLAGGIO { get; set; }
        public string GIORNI_DISPONIBILITA_SPEDIZIONE { get; set; }
        public string ORARI_DISPONIBILITA_SPEDIZIONE { get; set; }
        public Nullable<int> ID_INDIRIZZO_DESTINATARIO { get; set; }
        public string NOMINATIVO_DESTINATARIO { get; set; }
        public string TELEFONO_DESTINATARIO { get; set; }
        public string INFO_EXTRA_DESTINATARIO { get; set; }
        public int PUNTI { get; set; }
        public decimal SOLDI { get; set; }
        public Nullable<int> ID_TIPO_VALUTA { get; set; }
        public string EXTERNAL_ID_SPEDIZIONE { get; set; }
        public Nullable<int> ID_LDV { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual ALLEGATO ALLEGATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_TIPO_SCAMBIO_SPEDIZIONE> ANNUNCIO_TIPO_SCAMBIO_SPEDIZIONE { get; set; }
        public virtual CORRIERE_SERVIZIO CORRIERE_SERVIZIO { get; set; }
        public virtual TIPO_PACCO TIPO_PACCO { get; set; }
        public virtual TIPO_VALUTA TIPO_VALUTA { get; set; }
        public virtual INDIRIZZO INDIRIZZO { get; set; }
        public virtual INDIRIZZO INDIRIZZO1 { get; set; }
    }
}
