//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORRIERE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CORRIERE()
        {
            this.CORRIERE_COMUNE = new HashSet<CORRIERE_COMUNE>();
            this.CORRIERE_NAZIONE = new HashSet<CORRIERE_NAZIONE>();
            this.CORRIERE_PUNTO_SPEDIZIONE = new HashSet<CORRIERE_PUNTO_SPEDIZIONE>();
            this.CORRIERE_SERVIZIO = new HashSet<CORRIERE_SERVIZIO>();
            this.CORRIERE_TIPO_OGGETTO = new HashSet<CORRIERE_TIPO_OGGETTO>();
            this.CORRIERE_TIPO_PACCO = new HashSet<CORRIERE_TIPO_PACCO>();
            this.CORRIERE_PROVINCIA = new HashSet<CORRIERE_PROVINCIA>();
        }
    
        public int ID { get; set; }
        public int ID_TIPO_SPEDIZIONE { get; set; }
        public string NOME { get; set; }
        public string DESCRIZIONE { get; set; }
        public string CHIAVE { get; set; }
        public string PASSWORD { get; set; }
        public string NUMERO_LICENZA { get; set; }
        public string TOKEN { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public Nullable<int> STATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORRIERE_COMUNE> CORRIERE_COMUNE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORRIERE_NAZIONE> CORRIERE_NAZIONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORRIERE_PUNTO_SPEDIZIONE> CORRIERE_PUNTO_SPEDIZIONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORRIERE_SERVIZIO> CORRIERE_SERVIZIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORRIERE_TIPO_OGGETTO> CORRIERE_TIPO_OGGETTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORRIERE_TIPO_PACCO> CORRIERE_TIPO_PACCO { get; set; }
        public virtual TIPO_SPEDIZIONE TIPO_SPEDIZIONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORRIERE_PROVINCIA> CORRIERE_PROVINCIA { get; set; }
    }
}
