//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ERRORE
    {
        public int ID { get; set; }
        public string RICHIESTA { get; set; }
        public string RISPOSTA { get; set; }
        public string PARAMETRI { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public Nullable<int> ID_ATTIVITA { get; set; }
        public string CONTROLLER { get; set; }
        public string ACTION { get; set; }
        public string SESSIONE { get; set; }
        public string IP { get; set; }
        public string ALIAS { get; set; }
        public string MAC_ADDRESS { get; set; }
        public Nullable<System.DateTime> DATA_INSERIMENTO { get; set; }
    }
}
