//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_PAGAMENTO
    {
        public int ID { get; set; }
        public Nullable<int> ID_ANNUNCIO { get; set; }
        public string NOME_ANNUNCIO { get; set; }
        public Nullable<int> ID_COMPRATORE { get; set; }
        public string ID_PAGAMENTO { get; set; }
        public string ISTITUTO_PAGAMENTO { get; set; }
        public Nullable<System.DateTime> DATA_INSERIMENTO { get; set; }
        public string SESSIONE_COMPRATORE { get; set; }
    }
}
