//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODELLO()
        {
            this.OGGETTO_TELEFONO = new HashSet<OGGETTO_TELEFONO>();
            this.OGGETTO_COMPUTER = new HashSet<OGGETTO_COMPUTER>();
            this.OGGETTO_ELETTRODOMESTICO = new HashSet<OGGETTO_ELETTRODOMESTICO>();
            this.OGGETTO_GIOCO = new HashSet<OGGETTO_GIOCO>();
            this.OGGETTO_SPORT = new HashSet<OGGETTO_SPORT>();
            this.OGGETTO_STRUMENTO = new HashSet<OGGETTO_STRUMENTO>();
            this.OGGETTO_TECNOLOGIA = new HashSet<OGGETTO_TECNOLOGIA>();
            this.OGGETTO_VEICOLO = new HashSet<OGGETTO_VEICOLO>();
            this.RICERCA_OGGETTO_ELETTRODOMESTICO = new HashSet<RICERCA_OGGETTO_ELETTRODOMESTICO>();
            this.RICERCA_OGGETTO_GIOCO = new HashSet<RICERCA_OGGETTO_GIOCO>();
            this.RICERCA_OGGETTO_MODELLO = new HashSet<RICERCA_OGGETTO_MODELLO>();
            this.RICERCA_OGGETTO_PC = new HashSet<RICERCA_OGGETTO_PC>();
            this.RICERCA_OGGETTO_SPORT = new HashSet<RICERCA_OGGETTO_SPORT>();
            this.RICERCA_OGGETTO_STRUMENTI = new HashSet<RICERCA_OGGETTO_STRUMENTI>();
            this.RICERCA_OGGETTO_TECNOLOGIA = new HashSet<RICERCA_OGGETTO_TECNOLOGIA>();
            this.RICERCA_OGGETTO_TELEFONO = new HashSet<RICERCA_OGGETTO_TELEFONO>();
            this.RICERCA_OGGETTO_VEICOLO = new HashSet<RICERCA_OGGETTO_VEICOLO>();
        }
    
        public int ID { get; set; }
        public string NOME { get; set; }
        public string DESCRIZIONE { get; set; }
        public int ID_MARCA { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_TELEFONO> OGGETTO_TELEFONO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_COMPUTER> OGGETTO_COMPUTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_ELETTRODOMESTICO> OGGETTO_ELETTRODOMESTICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_GIOCO> OGGETTO_GIOCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_SPORT> OGGETTO_SPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_STRUMENTO> OGGETTO_STRUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_TECNOLOGIA> OGGETTO_TECNOLOGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_VEICOLO> OGGETTO_VEICOLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_ELETTRODOMESTICO> RICERCA_OGGETTO_ELETTRODOMESTICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_GIOCO> RICERCA_OGGETTO_GIOCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_MODELLO> RICERCA_OGGETTO_MODELLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_PC> RICERCA_OGGETTO_PC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_SPORT> RICERCA_OGGETTO_SPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_STRUMENTI> RICERCA_OGGETTO_STRUMENTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_TECNOLOGIA> RICERCA_OGGETTO_TECNOLOGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_TELEFONO> RICERCA_OGGETTO_TELEFONO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_VEICOLO> RICERCA_OGGETTO_VEICOLO { get; set; }
    }
}
