//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTIFICA()
        {
            this.ANNUNCIO_NOTIFICA = new HashSet<ANNUNCIO_NOTIFICA>();
        }
    
        public int ID { get; set; }
        public int ID_PERSONA { get; set; }
        public Nullable<int> ID_ATTIVITA { get; set; }
        public Nullable<int> ID_PERSONA_DESTINATARIO { get; set; }
        public Nullable<int> ID_ATTIVITA_DESTINATARIO { get; set; }
        public int MESSAGGIO { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public Nullable<System.DateTime> DATA_LETTURA { get; set; }
        public int STATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_NOTIFICA> ANNUNCIO_NOTIFICA { get; set; }
        public virtual ATTIVITA ATTIVITA { get; set; }
        public virtual ATTIVITA ATTIVITA1 { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual PERSONA PERSONA1 { get; set; }
    }
}
