//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFERTA_SPEDIZIONE
    {
        public int ID { get; set; }
        public int ID_OFFERTA { get; set; }
        public int ID_INDIRIZZO_DESTINATARIO { get; set; }
        public string NOMINATIVO_DESTINATARIO { get; set; }
        public string TELEFONO_DESTINATARIO { get; set; }
        public string INFO_EXTRA { get; set; }
        public string EMAIL { get; set; }
        public decimal SOLDI { get; set; }
        public int ID_TIPO_VALUTA { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
        public Nullable<int> ID_COMMISSIONE { get; set; }
    
        public virtual INDIRIZZO INDIRIZZO { get; set; }
        public virtual TIPO_VALUTA TIPO_VALUTA { get; set; }
        public virtual OFFERTA OFFERTA { get; set; }
        public virtual COMMISSIONE COMMISSIONE { get; set; }
    }
}
