//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGGETTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OGGETTO()
        {
            this.ANNUNCIO = new HashSet<ANNUNCIO>();
            this.OGGETTO_APPARTENENZA = new HashSet<OGGETTO_APPARTENENZA>();
            this.OGGETTO_COMPONENTE = new HashSet<OGGETTO_COMPONENTE>();
            this.OGGETTO_COMPUTER = new HashSet<OGGETTO_COMPUTER>();
            this.OGGETTO_CONSOLE = new HashSet<OGGETTO_CONSOLE>();
            this.OGGETTO_ELETTRODOMESTICO = new HashSet<OGGETTO_ELETTRODOMESTICO>();
            this.OGGETTO_GIOCO = new HashSet<OGGETTO_GIOCO>();
            this.OGGETTO_LIBRO = new HashSet<OGGETTO_LIBRO>();
            this.OGGETTO_MATERIALE = new HashSet<OGGETTO_MATERIALE>();
            this.OGGETTO_MUSICA = new HashSet<OGGETTO_MUSICA>();
            this.OGGETTO_SPORT = new HashSet<OGGETTO_SPORT>();
            this.OGGETTO_STRUMENTO = new HashSet<OGGETTO_STRUMENTO>();
            this.OGGETTO_TECNOLOGIA = new HashSet<OGGETTO_TECNOLOGIA>();
            this.OGGETTO_TELEFONO = new HashSet<OGGETTO_TELEFONO>();
            this.OGGETTO_VEICOLO = new HashSet<OGGETTO_VEICOLO>();
            this.OGGETTO_VESTITO = new HashSet<OGGETTO_VESTITO>();
            this.OGGETTO_VIDEO = new HashSet<OGGETTO_VIDEO>();
            this.OGGETTO_VIDEOGAMES = new HashSet<OGGETTO_VIDEOGAMES>();
        }
    
        public int ID { get; set; }
        public int NUMERO_PEZZI { get; set; }
        public int CONDIZIONE { get; set; }
        public Nullable<decimal> ALTEZZA { get; set; }
        public Nullable<decimal> LARGHEZZA { get; set; }
        public Nullable<decimal> LUNGHEZZA { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public Nullable<int> ANNO { get; set; }
        public string COLORE { get; set; }
        public Nullable<int> ID_MARCA { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO> ANNUNCIO { get; set; }
        public virtual MARCA MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_APPARTENENZA> OGGETTO_APPARTENENZA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_COMPONENTE> OGGETTO_COMPONENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_COMPUTER> OGGETTO_COMPUTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_CONSOLE> OGGETTO_CONSOLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_ELETTRODOMESTICO> OGGETTO_ELETTRODOMESTICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_GIOCO> OGGETTO_GIOCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_LIBRO> OGGETTO_LIBRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_MATERIALE> OGGETTO_MATERIALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_MUSICA> OGGETTO_MUSICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_SPORT> OGGETTO_SPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_STRUMENTO> OGGETTO_STRUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_TECNOLOGIA> OGGETTO_TECNOLOGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_TELEFONO> OGGETTO_TELEFONO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_VEICOLO> OGGETTO_VEICOLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_VESTITO> OGGETTO_VESTITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_VIDEO> OGGETTO_VIDEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_VIDEOGAMES> OGGETTO_VIDEOGAMES { get; set; }
    }
}
