//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYPAL_DETTAGLIO
    {
        public int ID { get; set; }
        public int ID_PAYPAL { get; set; }
        public string NOME { get; set; }
        public decimal IMPORTO { get; set; }
        public int QUANTITA { get; set; }
        public int STATO { get; set; }
    
        public virtual PAYPAL PAYPAL { get; set; }
    }
}
