//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA_SEGNALAZIONE
    {
        public int ID { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public string EMAIL_RISPOSTA { get; set; }
        public string OGGETTO { get; set; }
        public string TESTO { get; set; }
        public string ALLEGATO { get; set; }
        public string CONTROLLER { get; set; }
        public string VISTA { get; set; }
        public string IP { get; set; }
        public string MAC_ADDRESS { get; set; }
        public System.DateTime DATA_INVIO { get; set; }
        public int STATO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
