//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA_METODO_PAGAMENTO
    {
        public int ID { get; set; }
        public int ID_PERSONA { get; set; }
        public Nullable<int> ID_INDIRIZZO_FATTURAZIONE { get; set; }
        public string PAYER_ID { get; set; }
        public string EXTERNAL_CUSTOMER_ID { get; set; }
        public Nullable<int> CVV2 { get; set; }
        public string NOME { get; set; }
        public string COGNOME { get; set; }
        public string NUMERO { get; set; }
        public Nullable<int> TIPO_CARTA { get; set; }
        public Nullable<int> MESE { get; set; }
        public Nullable<int> ANNO { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual INDIRIZZO INDIRIZZO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
