//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RICERCA_OGGETTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RICERCA_OGGETTO()
        {
            this.RICERCA_OGGETTO_AUTORE = new HashSet<RICERCA_OGGETTO_AUTORE>();
            this.RICERCA_OGGETTO_CONSOLE = new HashSet<RICERCA_OGGETTO_CONSOLE>();
            this.RICERCA_OGGETTO_ELETTRODOMESTICO = new HashSet<RICERCA_OGGETTO_ELETTRODOMESTICO>();
            this.RICERCA_OGGETTO_GIOCO = new HashSet<RICERCA_OGGETTO_GIOCO>();
            this.RICERCA_OGGETTO_MODELLO = new HashSet<RICERCA_OGGETTO_MODELLO>();
            this.RICERCA_OGGETTO_MUSICA = new HashSet<RICERCA_OGGETTO_MUSICA>();
            this.RICERCA_OGGETTO_PC = new HashSet<RICERCA_OGGETTO_PC>();
            this.RICERCA_OGGETTO_SPORT = new HashSet<RICERCA_OGGETTO_SPORT>();
            this.RICERCA_OGGETTO_STRUMENTI = new HashSet<RICERCA_OGGETTO_STRUMENTI>();
            this.RICERCA_OGGETTO_TECNOLOGIA = new HashSet<RICERCA_OGGETTO_TECNOLOGIA>();
            this.RICERCA_OGGETTO_TELEFONO = new HashSet<RICERCA_OGGETTO_TELEFONO>();
            this.RICERCA_OGGETTO_VEICOLO = new HashSet<RICERCA_OGGETTO_VEICOLO>();
            this.RICERCA_OGGETTO_VESTITO = new HashSet<RICERCA_OGGETTO_VESTITO>();
            this.RICERCA_OGGETTO_VIDEO = new HashSet<RICERCA_OGGETTO_VIDEO>();
            this.RICERCA_OGGETTO_VIDEOGAMES = new HashSet<RICERCA_OGGETTO_VIDEOGAMES>();
        }
    
        public int ID { get; set; }
        public int ID_RICERCA { get; set; }
        public Nullable<int> STATO_OGGETTO { get; set; }
        public Nullable<int> ID_MARCA { get; set; }
        public Nullable<int> ANNO_MINIMO { get; set; }
        public Nullable<int> ANNO_MASSIMO { get; set; }
        public string COLORE { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        public virtual RICERCA RICERCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_AUTORE> RICERCA_OGGETTO_AUTORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_CONSOLE> RICERCA_OGGETTO_CONSOLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_ELETTRODOMESTICO> RICERCA_OGGETTO_ELETTRODOMESTICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_GIOCO> RICERCA_OGGETTO_GIOCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_MODELLO> RICERCA_OGGETTO_MODELLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_MUSICA> RICERCA_OGGETTO_MUSICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_PC> RICERCA_OGGETTO_PC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_SPORT> RICERCA_OGGETTO_SPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_STRUMENTI> RICERCA_OGGETTO_STRUMENTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_TECNOLOGIA> RICERCA_OGGETTO_TECNOLOGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_TELEFONO> RICERCA_OGGETTO_TELEFONO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_VEICOLO> RICERCA_OGGETTO_VEICOLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_VESTITO> RICERCA_OGGETTO_VESTITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_VIDEO> RICERCA_OGGETTO_VIDEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RICERCA_OGGETTO_VIDEOGAMES> RICERCA_OGGETTO_VIDEOGAMES { get; set; }
    }
}
