//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RICERCA_SERVIZIO
    {
        public int ID { get; set; }
        public int ID_RICERCA { get; set; }
        public Nullable<bool> LUNEDI { get; set; }
        public Nullable<bool> MARTEDI { get; set; }
        public Nullable<bool> MERCOLEDI { get; set; }
        public Nullable<bool> GIOVEDI { get; set; }
        public Nullable<bool> VENERDI { get; set; }
        public Nullable<bool> SABATO { get; set; }
        public Nullable<bool> DOMENICA { get; set; }
        public Nullable<bool> TUTTI { get; set; }
        public Nullable<int> TARIFFA { get; set; }
    
        public virtual RICERCA RICERCA { get; set; }
    }
}
