//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVIZIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVIZIO()
        {
            this.ANNUNCIO = new HashSet<ANNUNCIO>();
        }
    
        public int ID { get; set; }
        public int TARIFFA { get; set; }
        public Nullable<bool> LUNEDI { get; set; }
        public Nullable<bool> MARTEDI { get; set; }
        public Nullable<bool> MERCOLEDI { get; set; }
        public Nullable<bool> GIOVEDI { get; set; }
        public Nullable<bool> VENERDI { get; set; }
        public Nullable<bool> SABATO { get; set; }
        public Nullable<bool> DOMENICA { get; set; }
        public Nullable<bool> TUTTI { get; set; }
        public Nullable<System.TimeSpan> ORA_INIZIO_FERIALI { get; set; }
        public Nullable<System.TimeSpan> ORA_INIZIO_FESTIVI { get; set; }
        public Nullable<System.TimeSpan> ORA_FINE_FERIALI { get; set; }
        public Nullable<System.TimeSpan> ORA_FINE_FESTIVI { get; set; }
        public string SERVIZI_OFFERTI { get; set; }
        public string RISULTATI_FINALI { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO> ANNUNCIO { get; set; }
    }
}
