//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPEDIZIONE_INATTESA
    {
        public int ID { get; set; }
        public string NOME_ANNUNCIO { get; set; }
        public decimal PREZZO { get; set; }
        public string TITOLO { get; set; }
        public string COGNOME_RAGSOC { get; set; }
        public string NOME { get; set; }
        public string INFOUTILIXCONSEGNA { get; set; }
        public string VIA { get; set; }
        public string PIANOINTERNO { get; set; }
        public string CAP { get; set; }
        public string FRAZIONE { get; set; }
        public string COMUNE { get; set; }
        public string PROVINCIA { get; set; }
        public string IMPORTOCONTRASSEGNO { get; set; }
        public string MODALITACONTRASSEGNO { get; set; }
        public int COLLI { get; set; }
        public string TAGLIA { get; set; }
        public string CELLULARE { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public int RIFERIMENTO_CLIENTE { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string MITTENTE { get; set; }
        public string MITTENTE_NOME { get; set; }
        public string MITTENTE_VIA { get; set; }
        public string MITTENTE_CAP { get; set; }
        public string MITTENTE_COMUNE { get; set; }
        public string MITTENTE_PROVINCIA { get; set; }
        public string IMPORTOASSICURATA { get; set; }
        public string PRODOTTO { get; set; }
        public string SERVIZIO_RESI_EASY { get; set; }
    }
}
