//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSAZIONE_ANNUNCIO
    {
        public int ID { get; set; }
        public int ID_TRANSAZIONE { get; set; }
        public int ID_ANNUNCIO { get; set; }
        public Nullable<int> ID_COUPON { get; set; }
        public decimal PUNTI { get; set; }
        public decimal SOLDI { get; set; }
        public Nullable<decimal> PUNTI_SPEDIZIONE { get; set; }
        public Nullable<decimal> SOLDI_SPEDIZIONE { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual TRANSAZIONE TRANSAZIONE { get; set; }
        public virtual ANNUNCIO ANNUNCIO { get; set; }
    }
}
