//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enum() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GratisForGratis.App_GlobalResources.Enum", typeof(Enum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aprile.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Agosto.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore applicativo.
        /// </summary>
        public static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dicembre.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dollaro.
        /// </summary>
        public static string Dollar {
            get {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Euro.
        /// </summary>
        public static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Febbraio.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A mano.
        /// </summary>
        public static string HandleShipment {
            get {
                return ResourceManager.GetString("HandleShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assistenza.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gennaio.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Luglio.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giugno.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un mese.
        /// </summary>
        public static string LifeAd1 {
            get {
                return ResourceManager.GetString("LifeAd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un anno.
        /// </summary>
        public static string LifeAd12 {
            get {
                return ResourceManager.GetString("LifeAd12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Due mesi.
        /// </summary>
        public static string LifeAd2 {
            get {
                return ResourceManager.GetString("LifeAd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tre mesi.
        /// </summary>
        public static string LifeAd3 {
            get {
                return ResourceManager.GetString("LifeAd3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quattro mesi.
        /// </summary>
        public static string LifeAd4 {
            get {
                return ResourceManager.GetString("LifeAd4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cinque mesi.
        /// </summary>
        public static string LifeAd5 {
            get {
                return ResourceManager.GetString("LifeAd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei mesi.
        /// </summary>
        public static string LifeAd6 {
            get {
                return ResourceManager.GetString("LifeAd6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per sempre (A pagamento).
        /// </summary>
        public static string LifeAdInfinity {
            get {
                return ResourceManager.GetString("LifeAdInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Marzo.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Maggio.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Happy-Coin.
        /// </summary>
        public static string Moneta {
            get {
                return ResourceManager.GetString("Moneta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annuncio acquistato.
        /// </summary>
        public static string NotificationTypeAdPurchase {
            get {
                return ResourceManager.GetString("NotificationTypeAdPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annuncio venduto.
        /// </summary>
        public static string NotificationTypeAdSelled {
            get {
                return ResourceManager.GetString("NotificationTypeAdSelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offerta accettata.
        /// </summary>
        public static string NotificationTypeBidAccepted {
            get {
                return ResourceManager.GetString("NotificationTypeBidAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offerta ricevuta.
        /// </summary>
        public static string NotificationTypeBidReceveid {
            get {
                return ResourceManager.GetString("NotificationTypeBidReceveid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offerta rifiutata.
        /// </summary>
        public static string NotificationTypeBidRefused {
            get {
                return ResourceManager.GetString("NotificationTypeBidRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Personale.
        /// </summary>
        public static string NotificationTypeCustom {
            get {
                return ResourceManager.GetString("NotificationTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Novembre.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ottobre.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Online.
        /// </summary>
        public static string OnLineShipment {
            get {
                return ResourceManager.GetString("OnLineShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Privata.
        /// </summary>
        public static string PrivateShipment {
            get {
                return ResourceManager.GetString("PrivateShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reale.
        /// </summary>
        public static string RealMoney {
            get {
                return ResourceManager.GetString("RealMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settembre.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lunedì.
        /// </summary>
        public static string ShipDay1 {
            get {
                return ResourceManager.GetString("ShipDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Martedì.
        /// </summary>
        public static string ShipDay2 {
            get {
                return ResourceManager.GetString("ShipDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mercoledì.
        /// </summary>
        public static string ShipDay3 {
            get {
                return ResourceManager.GetString("ShipDay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giovedì.
        /// </summary>
        public static string ShipDay4 {
            get {
                return ResourceManager.GetString("ShipDay4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Venerdì.
        /// </summary>
        public static string ShipDay5 {
            get {
                return ResourceManager.GetString("ShipDay5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sabato.
        /// </summary>
        public static string ShipDay6 {
            get {
                return ResourceManager.GetString("ShipDay6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 10:00 - 11:00.
        /// </summary>
        public static string ShipHour10 {
            get {
                return ResourceManager.GetString("ShipHour10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 11:00 - 12:00.
        /// </summary>
        public static string ShipHour11 {
            get {
                return ResourceManager.GetString("ShipHour11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 12:00 - 13:00.
        /// </summary>
        public static string ShipHour12 {
            get {
                return ResourceManager.GetString("ShipHour12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 13:00 - 14:00.
        /// </summary>
        public static string ShipHour13 {
            get {
                return ResourceManager.GetString("ShipHour13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 14:00 - 15:00.
        /// </summary>
        public static string ShipHour14 {
            get {
                return ResourceManager.GetString("ShipHour14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 15:00 - 16:00.
        /// </summary>
        public static string ShipHour15 {
            get {
                return ResourceManager.GetString("ShipHour15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 16:00 - 17:00.
        /// </summary>
        public static string ShipHour16 {
            get {
                return ResourceManager.GetString("ShipHour16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 17:00 - 18:00.
        /// </summary>
        public static string ShipHour17 {
            get {
                return ResourceManager.GetString("ShipHour17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 18:00 - 19:00.
        /// </summary>
        public static string ShipHour18 {
            get {
                return ResourceManager.GetString("ShipHour18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 19:00 - 20:00.
        /// </summary>
        public static string ShipHour19 {
            get {
                return ResourceManager.GetString("ShipHour19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 09:00 - 10:00.
        /// </summary>
        public static string ShipHour9 {
            get {
                return ResourceManager.GetString("ShipHour9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spedizione.
        /// </summary>
        public static string Shipment {
            get {
                return ResourceManager.GetString("Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In attesa pagamento offerta.
        /// </summary>
        public static string StateSellPauseForBid {
            get {
                return ResourceManager.GetString("StateSellPauseForBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attiva.
        /// </summary>
        public static string StateShipmentActive {
            get {
                return ResourceManager.GetString("StateShipmentActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Eliminata.
        /// </summary>
        public static string StateShipmentDelete {
            get {
                return ResourceManager.GetString("StateShipmentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inattiva.
        /// </summary>
        public static string StateShipmentInactive {
            get {
                return ResourceManager.GetString("StateShipmentInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lettera di vettura.
        /// </summary>
        public static string StateShipmentLDV {
            get {
                return ResourceManager.GetString("StateShipmentLDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Effettuata.
        /// </summary>
        public static string StateShipmentOK {
            get {
                return ResourceManager.GetString("StateShipmentOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sospesa.
        /// </summary>
        public static string StateShipmentPause {
            get {
                return ResourceManager.GetString("StateShipmentPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pagata.
        /// </summary>
        public static string StateShipmentPay {
            get {
                return ResourceManager.GetString("StateShipmentPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attesa pagamento.
        /// </summary>
        public static string StateWaitingPayment {
            get {
                return ResourceManager.GetString("StateWaitingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Proposta.
        /// </summary>
        public static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un giorno.
        /// </summary>
        public static string TimePackage1 {
            get {
                return ResourceManager.GetString("TimePackage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Due giorni.
        /// </summary>
        public static string TimePackage2 {
            get {
                return ResourceManager.GetString("TimePackage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tre giorni.
        /// </summary>
        public static string TimePackage3 {
            get {
                return ResourceManager.GetString("TimePackage3", resourceCulture);
            }
        }
    }
}
