//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GratisForGratis.App_GlobalResources.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Acquisto fallito! Contatta l&apos;assistenza.
        /// </summary>
        public static string AdBuyFailed {
            get {
                return ResourceManager.GetString("AdBuyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Acquisto fallito! Controlla il credito a disposizione..
        /// </summary>
        public static string AdNotValid {
            get {
                return ResourceManager.GetString("AdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annuncio scaduto.
        /// </summary>
        public static string AdTimeOut {
            get {
                return ResourceManager.GetString("AdTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offerta non inviabile! Controlla il tuo credito o lo stato dell&apos;annuncio..
        /// </summary>
        public static string BidAd {
            get {
                return ResourceManager.GetString("BidAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore imprevisto.
        /// </summary>
        public static string BidComplete {
            get {
                return ResourceManager.GetString("BidComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a L&apos;offerta non è più valida!.
        /// </summary>
        public static string BidFailed {
            get {
                return ResourceManager.GetString("BidFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esiste già un&apos;offerta per questo annuncio.
        /// </summary>
        public static string BidInProgress {
            get {
                return ResourceManager.GetString("BidInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire dei crediti o almeno un baratto.
        /// </summary>
        public static string BidNotCorrect {
            get {
                return ResourceManager.GetString("BidNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire crediti o annunci da barattare.
        /// </summary>
        public static string BidPointsRequired {
            get {
                return ResourceManager.GetString("BidPointsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annuncio non acquistabile!.
        /// </summary>
        public static string BuyAd {
            get {
                return ResourceManager.GetString("BuyAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La lunghezza del messaggio dev&apos;essere compreso tra 1 e 10000 caratteri.
        /// </summary>
        public static string ChatLengthMessage {
            get {
                return ResourceManager.GetString("ChatLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cvv2 obbligatorio.
        /// </summary>
        public static string Cvv2 {
            get {
                return ResourceManager.GetString("Cvv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo obbligatorio.
        /// </summary>
        public static string DepartureAddressRequired {
            get {
                return ResourceManager.GetString("DepartureAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Città obbligatoria.
        /// </summary>
        public static string DepartureCityRequired {
            get {
                return ResourceManager.GetString("DepartureCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo scambio obbligatorio.
        /// </summary>
        public static string ExchangeModeRequired {
            get {
                return ResourceManager.GetString("ExchangeModeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire almeno un baratto!.
        /// </summary>
        public static string FieldEmptyBarters {
            get {
                return ResourceManager.GetString("FieldEmptyBarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo obbligatorio.
        /// </summary>
        public static string KidCard {
            get {
                return ResourceManager.GetString("KidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata annuncio obbligatoria.
        /// </summary>
        public static string LifeAdvertismentRequired {
            get {
                return ResourceManager.GetString("LifeAdvertismentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mese scadenza obbligatorio.
        /// </summary>
        public static string MounthExpiredCard {
            get {
                return ResourceManager.GetString("MounthExpiredCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mese errato.
        /// </summary>
        public static string MounthExpiredCardRange {
            get {
                return ResourceManager.GetString("MounthExpiredCardRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome obbligatorio.
        /// </summary>
        public static string NamePaymentCard {
            get {
                return ResourceManager.GetString("NamePaymentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero obbligatorio.
        /// </summary>
        public static string NumberCard {
            get {
                return ResourceManager.GetString("NumberCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo obbligatorio.
        /// </summary>
        public static string RecipientAddress {
            get {
                return ResourceManager.GetString("RecipientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cap obbligatorio.
        /// </summary>
        public static string RecipientCap {
            get {
                return ResourceManager.GetString("RecipientCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Civico obbligatorio.
        /// </summary>
        public static string RecipientCivic {
            get {
                return ResourceManager.GetString("RecipientCivic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info obbligatoria.
        /// </summary>
        public static string RecipientInfo {
            get {
                return ResourceManager.GetString("RecipientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome obbligatorio.
        /// </summary>
        public static string RecipientName {
            get {
                return ResourceManager.GetString("RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Telefono obbligatorio.
        /// </summary>
        public static string RecipientTelephone {
            get {
                return ResourceManager.GetString("RecipientTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E-mail o telefono già presenti.
        /// </summary>
        public static string RegisterExist {
            get {
                return ResourceManager.GetString("RegisterExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nominativo obbligatorio.
        /// </summary>
        public static string SellerNameRequired {
            get {
                return ResourceManager.GetString("SellerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Telefono obbligatorio.
        /// </summary>
        public static string SellerTelephoneRequired {
            get {
                return ResourceManager.GetString("SellerTelephoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per l&apos;indirizzo inserire tutti i dati (Citta, Via,Civico).
        /// </summary>
        public static string SettingsAddress {
            get {
                return ResourceManager.GetString("SettingsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giorni spedizione obbligatorio.
        /// </summary>
        public static string ShipDaysRequired {
            get {
                return ResourceManager.GetString("ShipDaysRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ore spedizione obbligatorio.
        /// </summary>
        public static string ShipHoursRequired {
            get {
                return ResourceManager.GetString("ShipHoursRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire almeno un corriere.
        /// </summary>
        public static string ShipmentCourierRequired {
            get {
                return ResourceManager.GetString("ShipmentCourierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità di spedizione obbligatoria.
        /// </summary>
        public static string ShipmentModeRequired {
            get {
                return ResourceManager.GetString("ShipmentModeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il valore minimo è 1.
        /// </summary>
        public static string ShipmentPriceNotValid {
            get {
                return ResourceManager.GetString("ShipmentPriceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prezzo spedizione obbligatorio.
        /// </summary>
        public static string ShipmentPriceRequired {
            get {
                return ResourceManager.GetString("ShipmentPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo spedizione obbligatoria.
        /// </summary>
        public static string ShipmentRequired {
            get {
                return ResourceManager.GetString("ShipmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cognome obbligatorio.
        /// </summary>
        public static string SurnamePaymentCard {
            get {
                return ResourceManager.GetString("SurnamePaymentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempo imballaggio obbligatorio.
        /// </summary>
        public static string TimePackageRequired {
            get {
                return ResourceManager.GetString("TimePackageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attiva l&apos;utente!.
        /// </summary>
        public static string UserEnabled {
            get {
                return ResourceManager.GetString("UserEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anno scadenza obbligatorio.
        /// </summary>
        public static string YearExpiredCard {
            get {
                return ResourceManager.GetString("YearExpiredCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a L&apos;anno dev&apos;essere maggiore o uguale a quello attuale.
        /// </summary>
        public static string YearExpiredCardRange {
            get {
                return ResourceManager.GetString("YearExpiredCardRange", resourceCulture);
            }
        }
    }
}
