//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GratisForGratis.App_GlobalResources.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annuncio non trovato!.
        /// </summary>
        public static string AdNotFound {
            get {
                return ResourceManager.GetString("AdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nel copiare l&apos;annuncio.
        /// </summary>
        public static string CopyAdvertising {
            get {
                return ResourceManager.GetString("CopyAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offerta baratto non aggiornata! ID offerta {0}. ID offerta-baratto {1}.
        /// </summary>
        public static string NotSavedBidBarter {
            get {
                return ResourceManager.GetString("NotSavedBidBarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salvataggio transazione fallita! ID offerta {0}.
        /// </summary>
        public static string NotSavedBidTransaction {
            get {
                return ResourceManager.GetString("NotSavedBidTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cedimento crediti per offerta fallito! ID offerta {0}. ID conto {1}.
        /// </summary>
        public static string NotSavedMoney {
            get {
                return ResourceManager.GetString("NotSavedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assegnamento crediti per offerta fallito! ID offerta {0}. ID conto {1}.
        /// </summary>
        public static string NotSavedMoneyForSeller {
            get {
                return ResourceManager.GetString("NotSavedMoneyForSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salvataggio crediti transazione fallita! ID offerta {0}. ID conto {1}.
        /// </summary>
        public static string NotSavedMoneyTransaction {
            get {
                return ResourceManager.GetString("NotSavedMoneyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante il salvataggio.
        /// </summary>
        public static string NotWishNotSave {
            get {
                return ResourceManager.GetString("NotWishNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nell&apos;apertura del form.
        /// </summary>
        public static string OpenCopyForm {
            get {
                return ResourceManager.GetString("OpenCopyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Orario d&apos;apertura errato.
        /// </summary>
        public static string OpenedHour {
            get {
                return ResourceManager.GetString("OpenedHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore dati mittente.
        /// </summary>
        public static string ShipmentDepartureError {
            get {
                return ResourceManager.GetString("ShipmentDepartureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spedizione fallita! Contattare assistenza o effettuare ritiro a mano..
        /// </summary>
        public static string ShipmentError {
            get {
                return ResourceManager.GetString("ShipmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Acquisto concluso ma la spedizione è fallita. Contatta la nostra assistenza!.
        /// </summary>
        public static string ShipmentFailed {
            get {
                return ResourceManager.GetString("ShipmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spedizione fuori servizio.
        /// </summary>
        public static string ShipmentServiceFailed {
            get {
                return ResourceManager.GetString("ShipmentServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sblocco fallito!.
        /// </summary>
        public static string UnblockFailed {
            get {
                return ResourceManager.GetString("UnblockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante il salvataggio.
        /// </summary>
        public static string WishNotSave {
            get {
                return ResourceManager.GetString("WishNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annuncio non in tuo possesso!.
        /// </summary>
        public static string YouDontHaveThisAd {
            get {
                return ResourceManager.GetString("YouDontHaveThisAd", resourceCulture);
            }
        }
    }
}
