//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetaTag {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetaTag() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GratisForGratis.App_GlobalResources.MetaTag", typeof(MetaTag).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hai dei dubbi o vuoi partecipare con noi a quest&apos;avventura? Inviaci una richiesta di colloquio. Amiamo la partecipazione sociale..
        /// </summary>
        public static string DescriptionContatti {
            get {
                return ResourceManager.GetString("DescriptionContatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} elimina disuguaglianze, rivaluta l&apos;usato e rivaluta le qualità personali dell&apos;individuo. Proponiamo un motore sociale per la crescita..
        /// </summary>
        public static string DescriptionCosaFacciamo {
            get {
                return ResourceManager.GetString("DescriptionCosaFacciamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Oggetti rotti, inutilizzati, utili per hobby o per la creazione di nuove idee, fantastici da regalare. Se vuoi puoi anche proporti per il volontariato e regalare un pò del tuo tempo..
        /// </summary>
        public static string DescriptionGift {
            get {
                return ResourceManager.GetString("DescriptionGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compra gratuitamente {0} della categoria {1}. In vendita a {2} con {3} crediti o prova con il baratto..
        /// </summary>
        public static string DescriptionGood {
            get {
                return ResourceManager.GetString("DescriptionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Acquista gratuitamente oggetti o servizi di qualsiasi tipo! Le migliori vendite gratuite del nostro portale..
        /// </summary>
        public static string DescriptionGratis {
            get {
                return ResourceManager.GetString("DescriptionGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Acquista gratuitamente gli oggetti che desideri. Compra servizi personali, aziendali o domestici e aumenta il tuo tempo libero..
        /// </summary>
        public static string DescriptionHome {
            get {
                return ResourceManager.GetString("DescriptionHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ecco l&apos;elenco delle grandi realtà che hanno deciso di incamminarsi insieme a noi! Progetti che migliorano la persona e il gruppo sociale..
        /// </summary>
        public static string DescriptionPartners {
            get {
                return ResourceManager.GetString("DescriptionPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il rispetto della privacy per noi è fondamentale. Ci teniamo a tutelare ogni vostro interesse prima del nostro..
        /// </summary>
        public static string DescriptionPrivacy {
            get {
                return ResourceManager.GetString("DescriptionPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grandi offerte su {1} della categoria {0}. Scopri le migliori novità gratuite o acquistabili con baratto. Regala, compra o scambia liberamente!.
        /// </summary>
        public static string DescriptionSearch {
            get {
                return ResourceManager.GetString("DescriptionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Potrai annullare la ricerca dal link presente nelle mail di notifica che riceverai oppure, se possiedi un profilo d&apos;accesso, direttamente dalla tua area privata..
        /// </summary>
        public static string DescriptionSearchSave {
            get {
                return ResourceManager.GetString("DescriptionSearchSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compra gratuitamente {0} della categoria {1}. In vendita a {2} con {3} crediti o prova con il baratto..
        /// </summary>
        public static string DescriptionService {
            get {
                return ResourceManager.GetString("DescriptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Siti web di utilità sociale ed umana.
        /// </summary>
        public static string DescriptionSiteWeb {
            get {
                return ResourceManager.GetString("DescriptionSiteWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contatti, dubbi, partecipare, partecipazione sociale, inviaci un tuo contatto.
        /// </summary>
        public static string KeywordsContatti {
            get {
                return ResourceManager.GetString("KeywordsContatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elimina le disuguaglianze, rivaluta oggetto, rivaluta servizi, crescita umana, spazio culturale, rinnovo dei beni.
        /// </summary>
        public static string KeywordsCosaFacciamo {
            get {
                return ResourceManager.GetString("KeywordsCosaFacciamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a oggetti rotti, oggetti inutilizzati, hobby, nuove idee, regalare, volontariato, tempo.
        /// </summary>
        public static string KeywordsGift {
            get {
                return ResourceManager.GetString("KeywordsGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compra gratuitamente, categoria, vendita, baratto, acquista, {0}, {1}, {2}, {3} crediti.
        /// </summary>
        public static string KeywordsGood {
            get {
                return ResourceManager.GetString("KeywordsGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tutto gratis, oggetti gratis, servizi gratis, acquista gratuitamente, vendite gratuite.
        /// </summary>
        public static string KeywordsGratis {
            get {
                return ResourceManager.GetString("KeywordsGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compra gratis, acquista gratuitamente, oggetti, compra servizi, compra arredamento,compra abbigliamento, compra musica, compra giochi, compra sport e tempo libero, compra elettronica, compra videoteca, compra cartoleria e libreria, compra veicoli, compra fai da te, compra servizi domestici, compra servizi aziendali, compra servizi per la persona.
        /// </summary>
        public static string KeywordsHome {
            get {
                return ResourceManager.GetString("KeywordsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grandi realtà, miglioramento della persona, gruppo sociale, Jadenka, DavideMilitano, PsicologiADomicilio, AvvocatoClick, Totallympics, CultID Studio.
        /// </summary>
        public static string KeywordsPartners {
            get {
                return ResourceManager.GetString("KeywordsPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Privacy, condizioni, persona, {0}, tutela legale, informazioni.
        /// </summary>
        public static string KeywordsPrivacy {
            get {
                return ResourceManager.GetString("KeywordsPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gratis, offerte, oggetti, cerca, beni, servizi, baratto, scambio, {0}.
        /// </summary>
        public static string KeywordsSearch {
            get {
                return ResourceManager.GetString("KeywordsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compra gratuitamente, categoria, vendita, baratto, acquista, {0}, {1}, {2}, {3} crediti.
        /// </summary>
        public static string KeywordsService {
            get {
                return ResourceManager.GetString("KeywordsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Siti utili, Utilità sociale, Utilità umana, JustKnock, TaskyJob, GeniUp, WikiLeaks.
        /// </summary>
        public static string KeywordsSiteWeb {
            get {
                return ResourceManager.GetString("KeywordsSiteWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chat personale.
        /// </summary>
        public static string TitleChatIndex {
            get {
                return ResourceManager.GetString("TitleChatIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chat con {0}.
        /// </summary>
        public static string TitleChatUser {
            get {
                return ResourceManager.GetString("TitleChatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il primo e-commerce che non vende, ma regala!.
        /// </summary>
        public static string TitleGeneric {
            get {
                return ResourceManager.GetString("TitleGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Regala ciò che non usi più o fai volontariato!.
        /// </summary>
        public static string TitleGift {
            get {
                return ResourceManager.GetString("TitleGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gratis {0} della categoria {1}. Acquista o Baratta..
        /// </summary>
        public static string TitleGood {
            get {
                return ResourceManager.GetString("TitleGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una nuovissima e unica moneta virtuale!.
        /// </summary>
        public static string TitleOnlineMoney {
            get {
                return ResourceManager.GetString("TitleOnlineMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profilo di {0}.
        /// </summary>
        public static string TitleProfile {
            get {
                return ResourceManager.GetString("TitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offerte rifiutate.
        /// </summary>
        public static string TitleRefusedBid {
            get {
                return ResourceManager.GetString("TitleRefusedBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salvataggio fallito!.
        /// </summary>
        public static string TitleSaveSearchKO {
            get {
                return ResourceManager.GetString("TitleSaveSearchKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cerca {0} GRATIS o BARATTO.
        /// </summary>
        public static string TitleSearch {
            get {
                return ResourceManager.GetString("TitleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerche salvate.
        /// </summary>
        public static string TitleSearchSaved {
            get {
                return ResourceManager.GetString("TitleSearchSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tutto gratis! oggetti e servizi gratis con gli {0}!.
        /// </summary>
        public static string TitleSellGratis {
            get {
                return ResourceManager.GetString("TitleSellGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gratis {0} della categoria {1}. Acquista o Baratta..
        /// </summary>
        public static string TitleService {
            get {
                return ResourceManager.GetString("TitleService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Siti utili.
        /// </summary>
        public static string TitleSiteWeb {
            get {
                return ResourceManager.GetString("TitleSiteWeb", resourceCulture);
            }
        }
    }
}
