//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModel() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GratisForGratis.App_GlobalResources.ViewModel", typeof(ViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun LDV.
        /// </summary>
        public static string AdNothingLDV {
            get {
                return ResourceManager.GetString("AdNothingLDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Baratto asincrono.
        /// </summary>
        public static string BarterAsyncLink {
            get {
                return ResourceManager.GetString("BarterAsyncLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Baratto.
        /// </summary>
        public static string BarterLink {
            get {
                return ResourceManager.GetString("BarterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Baratto multilaterale.
        /// </summary>
        public static string BarterMultilateralLink {
            get {
                return ResourceManager.GetString("BarterMultilateralLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Baratto / Offerta.
        /// </summary>
        public static string BartLink {
            get {
                return ResourceManager.GetString("BartLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Puoi offrire solo tuoi annunci pubblicati con l&apos;opzione di spedizione..
        /// </summary>
        public static string BidOnlyAdShipment {
            get {
                return ResourceManager.GetString("BidOnlyAdShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offerte ricevute.
        /// </summary>
        public static string BidsAd {
            get {
                return ResourceManager.GetString("BidsAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome annuncio.
        /// </summary>
        public static string BidsAdName {
            get {
                return ResourceManager.GetString("BidsAdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Proponi un tuo annuncio già in vendita.
        /// </summary>
        public static string BidYourAd {
            get {
                return ResourceManager.GetString("BidYourAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BitCoin.
        /// </summary>
        public static string BitCoin {
            get {
                return ResourceManager.GetString("BitCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data invio.
        /// </summary>
        public static string ChatDate {
            get {
                return ResourceManager.GetString("ChatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data ultima modifica.
        /// </summary>
        public static string ChatDateUpdate {
            get {
                return ResourceManager.GetString("ChatDateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun messaggio =( Inizia una nuova conversazione!.
        /// </summary>
        public static string ChatEmpty {
            get {
                return ResourceManager.GetString("ChatEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Messaggio.
        /// </summary>
        public static string ChatMessage {
            get {
                return ResourceManager.GetString("ChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Destinatario.
        /// </summary>
        public static string ChatRecipient {
            get {
                return ResourceManager.GetString("ChatRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mittente.
        /// </summary>
        public static string ChatSender {
            get {
                return ResourceManager.GetString("ChatSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annulla modifica.
        /// </summary>
        public static string ChatUpdateCancel {
            get {
                return ResourceManager.GetString("ChatUpdateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Economia circolare.
        /// </summary>
        public static string CircularEconomy {
            get {
                return ResourceManager.GetString("CircularEconomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assistenza.
        /// </summary>
        public static string ContactsLink {
            get {
                return ResourceManager.GetString("ContactsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lista corrieri.
        /// </summary>
        public static string CourierList {
            get {
                return ResourceManager.GetString("CourierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cvv2.
        /// </summary>
        public static string Cvv2 {
            get {
                return ResourceManager.GetString("Cvv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dati carta prepagata.
        /// </summary>
        public static string DataPaymentCard {
            get {
                return ResourceManager.GetString("DataPaymentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Via/Viale/Piazza....
        /// </summary>
        public static string DepartureAddress {
            get {
                return ResourceManager.GetString("DepartureAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comune.
        /// </summary>
        public static string DepartureCity {
            get {
                return ResourceManager.GetString("DepartureCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Civico.
        /// </summary>
        public static string DepartureCivic {
            get {
                return ResourceManager.GetString("DepartureCivic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info mittente (Referente, piano ecc...).
        /// </summary>
        public static string DepartureInfo {
            get {
                return ResourceManager.GetString("DepartureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Come guadagnare.
        /// </summary>
        public static string EarnMoneyLink {
            get {
                return ResourceManager.GetString("EarnMoneyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A mano.
        /// </summary>
        public static string ExchangeHand {
            get {
                return ResourceManager.GetString("ExchangeHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo scambio.
        /// </summary>
        public static string ExchangeMode {
            get {
                return ResourceManager.GetString("ExchangeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Con spedizione.
        /// </summary>
        public static string ExchangeShip {
            get {
                return ResourceManager.GetString("ExchangeShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Circuito del gratuito.
        /// </summary>
        public static string FreeCircuitLink {
            get {
                return ResourceManager.GetString("FreeCircuitLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finanziamenti.
        /// </summary>
        public static string FundingLink {
            get {
                return ResourceManager.GetString("FundingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Regalare.
        /// </summary>
        public static string GiftLink {
            get {
                return ResourceManager.GetString("GiftLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decrescita felice.
        /// </summary>
        public static string HappyDegrowth {
            get {
                return ResourceManager.GetString("HappyDegrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HappyPeople.
        /// </summary>
        public static string HappyPeople {
            get {
                return ResourceManager.GetString("HappyPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lascia un feedback.
        /// </summary>
        public static string HomeUserFeedback {
            get {
                return ResourceManager.GetString("HomeUserFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alla fine di una compravendita, rilascia un tuo giudizio.
        /// </summary>
        public static string HomeUserFeedbackInfo {
            get {
                return ResourceManager.GetString("HomeUserFeedbackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pubblica annunci completi.
        /// </summary>
        public static string HomeUserFullAd {
            get {
                return ResourceManager.GetString("HomeUserFullAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci tutti i dati, anche quelli opzionali.
        /// </summary>
        public static string HomeUserFullAdInfo {
            get {
                return ResourceManager.GetString("HomeUserFullAdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Collega il tuo profilo a Facebook.
        /// </summary>
        public static string HomeUserJoinSocial {
            get {
                return ResourceManager.GetString("HomeUserJoinSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Potrai guadagnare dagli annunci postati anche sul social network.
        /// </summary>
        public static string HomeUserJoinSocialInfo {
            get {
                return ResourceManager.GetString("HomeUserJoinSocialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Posta oggetti da vendere.
        /// </summary>
        public static string HomeUserPublishGood {
            get {
                return ResourceManager.GetString("HomeUserPublishGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inutilizzati, indesiderati, ecc...
        /// </summary>
        public static string HomeUserPublishGoodInfo {
            get {
                return ResourceManager.GetString("HomeUserPublishGoodInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Posta le tue competenze.
        /// </summary>
        public static string HomeUserPublishService {
            get {
                return ResourceManager.GetString("HomeUserPublishService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hobby, Professionali, ecc...
        /// </summary>
        public static string HomeUserPublishServiceInfo {
            get {
                return ResourceManager.GetString("HomeUserPublishServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Segnala bug del sito.
        /// </summary>
        public static string HomeUserSendBug {
            get {
                return ResourceManager.GetString("HomeUserSendBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In caso riscontrato da una buona percentuale di utenti, verranno versati crediti.
        /// </summary>
        public static string HomeUserSendBugInfo {
            get {
                return ResourceManager.GetString("HomeUserSendBugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Come funziona.
        /// </summary>
        public static string HowWorkLink {
            get {
                return ResourceManager.GetString("HowWorkLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo.
        /// </summary>
        public static string KidCard {
            get {
                return ResourceManager.GetString("KidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Messaggi.
        /// </summary>
        public static string LayoutChat {
            get {
                return ResourceManager.GetString("LayoutChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata annuncio.
        /// </summary>
        public static string LifeAdvertisment {
            get {
                return ResourceManager.GetString("LifeAdvertisment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accedi o Registrati.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accedi con FaceBook.
        /// </summary>
        public static string LoginFacebook {
            get {
                return ResourceManager.GetString("LoginFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password dimenticata?.
        /// </summary>
        public static string LoginPasswordForgot {
            get {
                return ResourceManager.GetString("LoginPasswordForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Registrazione completa.
        /// </summary>
        public static string LoginRegistration {
            get {
                return ResourceManager.GetString("LoginRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Missione.
        /// </summary>
        public static string MissionLink {
            get {
                return ResourceManager.GetString("MissionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mese scadenza.
        /// </summary>
        public static string MounthExpiredCard {
            get {
                return ResourceManager.GetString("MounthExpiredCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome titolare.
        /// </summary>
        public static string NamePaymentCard {
            get {
                return ResourceManager.GetString("NamePaymentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data notifica.
        /// </summary>
        public static string NewsInsertDate {
            get {
                return ResourceManager.GetString("NewsInsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipologia.
        /// </summary>
        public static string NewsName {
            get {
                return ResourceManager.GetString("NewsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data lettura.
        /// </summary>
        public static string NewsReadDate {
            get {
                return ResourceManager.GetString("NewsReadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accetta offerte.
        /// </summary>
        public static string NoBid {
            get {
                return ResourceManager.GetString("NoBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero.
        /// </summary>
        public static string NumberCard {
            get {
                return ResourceManager.GetString("NumberCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Criptovaluta.
        /// </summary>
        public static string OnlineMoneyLink {
            get {
                return ResourceManager.GetString("OnlineMoneyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Partnership.
        /// </summary>
        public static string PartnershipLink {
            get {
                return ResourceManager.GetString("PartnershipLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Privacy.
        /// </summary>
        public static string PrivacyLink {
            get {
                return ResourceManager.GetString("PrivacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invia messaggio.
        /// </summary>
        public static string ProfileSendMessage {
            get {
                return ResourceManager.GetString("ProfileSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Top acquisti.
        /// </summary>
        public static string ProfileTopPurchases {
            get {
                return ResourceManager.GetString("ProfileTopPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Top desideri.
        /// </summary>
        public static string ProfileTopWishes {
            get {
                return ResourceManager.GetString("ProfileTopWishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Al costo della spedizione verrà applicata una &lt;span style=&quot;color:red;font-weight:bold;&quot;&gt;commissione del 10%&lt;/span&gt;.
        /// </summary>
        public static string PublishAdInfoShipment {
            get {
                return ResourceManager.GetString("PublishAdInfoShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visualizza inserimento dati aggiuntivi (anche per la spedizione).
        /// </summary>
        public static string PublishCheckInfoExtra {
            get {
                return ResourceManager.GetString("PublishCheckInfoExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Se il tuo account è collegato a quello di Facebook &lt;b&gt;guadagnerai HappyCoin&lt;/b&gt; omaggio!.
        /// </summary>
        public static string PublishInfoFB {
            get {
                return ResourceManager.GetString("PublishInfoFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INFO SPEDIZIONE.
        /// </summary>
        public static string PublishTitleShipment {
            get {
                return ResourceManager.GetString("PublishTitleShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dati spedizione.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Via/Viale/Piazza....
        /// </summary>
        public static string RecipientAddress {
            get {
                return ResourceManager.GetString("RecipientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cap.
        /// </summary>
        public static string RecipientCap {
            get {
                return ResourceManager.GetString("RecipientCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Civico.
        /// </summary>
        public static string RecipientCivic {
            get {
                return ResourceManager.GetString("RecipientCivic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info (Referente, piano ecc...).
        /// </summary>
        public static string RecipientInfo {
            get {
                return ResourceManager.GetString("RecipientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nominativo.
        /// </summary>
        public static string RecipientName {
            get {
                return ResourceManager.GetString("RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Telefono.
        /// </summary>
        public static string RecipientTelephone {
            get {
                return ResourceManager.GetString("RecipientTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attenzione agli &lt;b&gt;spazi&lt;/b&gt; soprattutto nei campi telefono o e-mail!.
        /// </summary>
        public static string RegisterInfo {
            get {
                return ResourceManager.GetString("RegisterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vuoi fare una registrazione PIù RAPIDA?!?! &gt;&gt;&gt;.
        /// </summary>
        public static string RegisterLinkSpeed {
            get {
                return ResourceManager.GetString("RegisterLinkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rimetti in vendita.
        /// </summary>
        public static string Resell {
            get {
                return ResourceManager.GetString("Resell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il &lt;b&gt;salvataggio&lt;/b&gt; della ricerca effettuata è &lt;b&gt;fallito&lt;/b&gt;. &lt;br /&gt;&lt;b&gt;Ritentare&lt;/b&gt; più tardi o contattare la nostra &lt;b&gt;assistenza&lt;/b&gt; tramite il popup apposito..
        /// </summary>
        public static string SaveSearchKO {
            get {
                return ResourceManager.GetString("SaveSearchKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non sei &lt;b&gt;soddisfatto&lt;/b&gt; della tua &lt;b&gt;ricerca&lt;/b&gt;?&lt;br/&gt;&lt;b&gt;Salvala&lt;/b&gt; e verrai avvisato sulle novità!.
        /// </summary>
        public static string SearchNotLike {
            get {
                return ResourceManager.GetString("SearchNotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sicurezza.
        /// </summary>
        public static string SecurityLink {
            get {
                return ResourceManager.GetString("SecurityLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nominativo.
        /// </summary>
        public static string SellerName {
            get {
                return ResourceManager.GetString("SellerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Telefono.
        /// </summary>
        public static string SellerTelephone {
            get {
                return ResourceManager.GetString("SellerTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vendere senza denaro.
        /// </summary>
        public static string SellGratisLink {
            get {
                return ResourceManager.GetString("SellGratisLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Collegato a FB!.
        /// </summary>
        public static string SettingsJoinToFB {
            get {
                return ResourceManager.GetString("SettingsJoinToFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giorni per la spedizione.
        /// </summary>
        public static string ShipDays {
            get {
                return ResourceManager.GetString("ShipDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ore per la spedizione.
        /// </summary>
        public static string ShipHours {
            get {
                return ResourceManager.GetString("ShipHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ulteriori info sulla spedizione.
        /// </summary>
        public static string ShipmentDescription {
            get {
                return ResourceManager.GetString("ShipmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spedizione a mano.
        /// </summary>
        public static string ShipmentHand {
            get {
                return ResourceManager.GetString("ShipmentHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spedizione.
        /// </summary>
        public static string ShipmentLink {
            get {
                return ResourceManager.GetString("ShipmentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità di spedizione.
        /// </summary>
        public static string ShipmentMode {
            get {
                return ResourceManager.GetString("ShipmentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spedizione da portale.
        /// </summary>
        public static string ShipmentOnline {
            get {
                return ResourceManager.GetString("ShipmentOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prezzo spedizione.
        /// </summary>
        public static string ShipmentPrice {
            get {
                return ResourceManager.GetString("ShipmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spedizione privata.
        /// </summary>
        public static string ShipmentPrivate {
            get {
                return ResourceManager.GetString("ShipmentPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Servizio spedizione.
        /// </summary>
        public static string ShippingService {
            get {
                return ResourceManager.GetString("ShippingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Siti utili.
        /// </summary>
        public static string SiteWebLink {
            get {
                return ResourceManager.GetString("SiteWebLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cognome titolare.
        /// </summary>
        public static string SurnamePaymentCard {
            get {
                return ResourceManager.GetString("SurnamePaymentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Squadra.
        /// </summary>
        public static string TeamLink {
            get {
                return ResourceManager.GetString("TeamLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempo imballaggio.
        /// </summary>
        public static string TimePackage {
            get {
                return ResourceManager.GetString("TimePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiorna prezzo.
        /// </summary>
        public static string UpdateShipmentPrice {
            get {
                return ResourceManager.GetString("UpdateShipmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Perchè G4G?.
        /// </summary>
        public static string WhySiteLink {
            get {
                return ResourceManager.GetString("WhySiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anno scadenza.
        /// </summary>
        public static string YearExpiredCard {
            get {
                return ResourceManager.GetString("YearExpiredCard", resourceCulture);
            }
        }
    }
}
